tests:
  - name: decompress success test
    target_processors: '/pipeline/processors'
    environment: { }
    input_batch:
      - content: '{"tokenId":431,"timestamp":"2024-04-18T17:20:26.633Z","name":"powertrainCombustionEngineECT","valueNumber":107,"valueString":"","source":"0xbA5738a18d83D41847dfFbDC6101d37C69c9B0cF"}'
    output_batches:
      - - json_equals: '[431,"2024-04-18T17:20:26.633Z","powertrainCombustionEngineECT", "0xbA5738a18d83D41847dfFbDC6101d37C69c9B0cF",107,""]'
 # - name: decompress wrong signature test
#    target_processors: '/pipeline/processors'
#    environment: { }
#    input_batch:
#      - content: '{"compressedPayload": "H4sIAAAAAAAA/6yWb2/bNhDGvwtfKyqPvOMfvc2fYVuLZqvbDBuGgqZOjhZLMiTaW1b4uw9yDNstoiFz5leGeb+Hz50fkfoi6lIUQlU/vm9vYXb39xo/hkd1V3/3U/XD1c/9XSsyMXTrPrIoRKgS903oHzi9KXlTR34zpJDWw1i04rjhfqi7VhQCcjn+tp7/wTGJQsi/vLuyrrQAl5IjId6Yak4lYRUrQ+QvbxAITfAiE6luxt2UVHgh8QL8DGwhbYEuR6mtkwbg17HucTXWxa7Jy7rp8idL+dFSvWhDWve8M4CaqrmL3paSY2Uss7Ts55UhhojoKwguqEAePNE8AJHSVQBHLigtuZLluOyNR8RSRZDE82h8GdkSumjBhqqKCqI0WBnU86AjeSRjdekrpyCKTJQhBVF82bU4pNCsRAEWNKFB41DqTDw1Mdb0q/rjaiz8wHEY61wm5iEl7h8/dcsUFiwKULkx20xs+L6Oyx2263o5iOK3Z7dB7VFnog3NfnZNaEsurxe9yMQmLNcsCpI5eCOtQw3aKsJt9ryWcWgPWk2ojhJoKUc7xVntzYHbe/+wYi6PAmBgkvboDzS3i7rlt104ZVVO6EFNCTh0R9vpvu9SWvJtN9RpTO9BRtncodZmSsZLdexiuO/6dLPm5ayvm6+tTPLkjzbqNoUHnnGzOoGnBkgSlPsGve15GMawH3A9NQDSUqkD3q9O/GpJJrdTlok84OsnR84aPCM35LWEs3x7h/LswBmpnXxN4Iz04F+RFANI9O9JmUSVlOb8pBj0Up4zcUOo/euTYsg7+J9Oq/0Bu9dadu2iTuvyZAoXFnKSYJTT+8/LlEL6RghVrqwEqf+Tzn3Znf6j+cv6aIeQjtTUk/M18+cqfB5vyRPL4vL9u9u317PrK/EiiWGoT/IvbupuuPjUqsW7z9e/zMT29+3xUpp1D9x+fyUKmYkmPIzlIhNNV/Ly6esjh363enx/2EAucym2/wQAAP//oQmw9aAIAAA="}'
##     todo: add assertion that there are no output batches
